name: Issue Event Workflow
on:
    issues:
        types:
            - opened
            - closed

jobs:
    issue_event_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Echo Issue Event
              run: |
                    echo "Issue Event: ${{ github.event_name }}"
                    echo "Issue Number: ${{ github.event.issue.number }}"
                    echo "Issue Title: ${{ github.event.issue.title }}"
                    echo "Issue Body: ${{ github.event.issue.body }}"
